version: '3'

services:
  web:
    image: evgfitil/api_yamdb
    command: python manage.py runserver 0.0.0.0:8000
    container_name: yamdb-web
    volumes:
      - .:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:12.0-alpine
    container_name: yamdb-db
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .db.env
  
volumes:
  postgres_data:
