# This is a basic workflow to help you get started with Actions

name: YAMDB-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Lint wiht flake8
        run: flake8 . --exclude=./api/migrations/*,./api_yamdb/settings.py,./tests/*

  push_to_docker_hub:
    name: Push images to the Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1

      - name: Push to the Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: ./
          dockerfile: ./Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: evgfitil/api_yamdb
          tag_with_ref: true